### ISSUE TITLE
3D printed bracket

### ISSUE THREAD

**Issue by giobbino** [skiselev/isa-super-vga#2]
For anybody who wish to print its own bracket, I released an STL file on Thingiverse:

https://www.thingiverse.com/thing:6473572

The same object also fits the Floppy disk and serial controller by Sergey.

hope it could help.

**Comment by skiselev** [comment]
That looks great.
I've added it to the BoM.
Also added it to the [Monster FDC](https://github.com/skiselev/monster-fdc) project that uses the same bracket.
Thank you!
